cfpb/wagtail-treemodeladmin

- .gitattributes
- .travis.yml
- MANIFEST.in
- README.md
- setup.py
- tox.ini
- treemodeladmin/__init__.py
- treemodeladmin/apps.py
- treemodeladmin/helpers.py
- treemodeladmin/options.py
- treemodeladmin/templates/treemodeladmin/includes/breadcrumb.html
- treemodeladmin/templates/treemodeladmin/includes/header.html
- treemodeladmin/templates/treemodeladmin/includes/tree_result_list.html
- treemodeladmin/templates/treemodeladmin/includes/tree_result_row.html
- treemodeladmin/templates/treemodeladmin/index.html
- treemodeladmin/templatetags/treemodeladmin_tags.py
- treemodeladmin/tests/settings.py
- treemodeladmin/tests/test_options.py
- treemodeladmin/tests/test_views.py
- treemodeladmin/tests/treemodeladmintest/apps.py
- treemodeladmin/tests/treemodeladmintest/fixtures/treemodeladmin_test.json
- treemodeladmin/tests/treemodeladmintest/migrations/0001_initial.py
- treemodeladmin/tests/treemodeladmintest/models.py
- treemodeladmin/tests/treemodeladmintest/wagtail_hooks.py
- treemodeladmin/tests/urls.py
- treemodeladmin/views.py
This PR adds the initial version of wagtail-treemodeladmin. [The README](https://github.com/cfpb/wagtail-treemodeladmin/blob/initial-work/README.md) hopefully provides a decent overview of what this is.
> Wagtail-TreeModelAdmin is an extension for Wagtail's ModelAdmin that allows for a page explorer-like navigation of Django model relationships within the Wagtail admin.
Implementationally, I've tried to make this as light-weight as possible. It extends ModelAdmin as little as possible to allow page explorer-style navigation from one model to another via a configured `ForeignKey` one-to-many relationship. It does this by having the fields for that relationship explicitly configured on the `TreeModelAdmin` subclass, and then adding the `>` column to the right of the object listing table as …
> Add initial version of wagtail-treemodeladmin

- README.md
- treemodeladmin/helpers.py
- treemodeladmin/options.py
- treemodeladmin/templates/treemodeladmin/includes/header.html
- treemodeladmin/templates/treemodeladmin/includes/tree_result_row.html
- treemodeladmin/templates/treemodeladmin/index.html
- treemodeladmin/templatetags/treemodeladmin_tags.py
- treemodeladmin/tests/test_views.py
- treemodeladmin/views.py
This PR adds support for maintaining parent selection while navigating the tree in breadcrumbs and when creating a new child.
- Clicking on a model name in the breadcrumbs while having a parent selected will maintain the parent selection throughout the tree.
- Creating a new child from a page with a parent selection (either the + button on an empty parent or the "Add {Model Name}" button) will have that field in the creation form filled out with the selected parent. 
- Editing a child will redirect to the parent-filtered listing page.
- Deleting a child will redirect to the parent-filtered listing page.
- Fixed the "Edit" button under the parent name. Previously it was editing the child object with the parent's primary key.
- Refactored some of the TreeIndexView parent logic into a mixin …
> Support parent selection in breadcrumb navigation and new child creation

- treemodeladmin/options.py
- treemodeladmin/tests/test_views.py
- treemodeladmin/tests/treemodeladmintest/fixtures/treemodeladmin_test.json
- treemodeladmin/tests/treemodeladmintest/migrations/0001_initial.py
- treemodeladmin/tests/treemodeladmintest/models.py
- treemodeladmin/tests/treemodeladmintest/wagtail_hooks.py
- treemodeladmin/views.py
Parent breadcrumbs were broken below the first set of children (basically after the first loop). This PR fixes it.
- Breadcrumbs two-levels or deeper now include the ancestral parent filter in the link
> Fix parent breadcrumbs

- setup.py
- treemodeladmin/static/treemodeladmin/css/index.css
Align content in admin tables to the top of cells (except the final "children" cells so that the arrow/plus icons stay centered).
- Align admin content to top of cells.
Before:
After:
- Wagtail core [hardcodes](https://github.com/wagtail/wagtail/search?q=valign&unscoped_q=valign) vertical alignment in the templates instead of using CSS. CSS seems preferable.
> Vertically align content in admin table

- setup.py
- treemodeladmin/helpers.py
- treemodeladmin/tests/test_views.py
- treemodeladmin/views.py
This PR changes the way TreeModelAdmin generates breadcrumbs. Where before the crumbs would include only the plural name of the parent models, even if we're "inside" a particular parent. This PR changes the breadcrumbs to display `str(parent_instance)` instead of the plural name of the model.
The test app before:
The test app after:
I've bumped the version number in `setup.py` in anticipation of releasing this.
> Make breadcrumbs show specific parents when they exist

- .travis.yml
- README.md
- setup.py
- tox.ini
- treemodeladmin/options.py
- treemodeladmin/static/treemodeladmin/css/index.css
- treemodeladmin/tests/test_options.py
- treemodeladmin/tests/urls.py
- treemodeladmin/views.py
This PR fixes #8, where action buttons only appear when their column is hovered. The standard Wagtail ModelAdmin behavior is to show action buttons whenever the entire row is hovered. This is fixed by ensuring that we inherit ModelAdmin's default index CSS. 
This PR also includes some minor changes to the TreeModelAdmin CSS that are required now that we're inheriting ModelAdmin's CSS.
I've also included support for Django 2.1 and Wagtail 2.1 and 2.2.
> Fix hover bug

- treemodeladmin/static/treemodeladmin/css/index.css
This change alters the CSS to properly vertically center the plus sign icon that appears when a menu item has no children. Currently this icon is aligned to the top, which feels wrong and is inconsistent with how this icon appears in the Wagtail page browser.
Before:
After:
> Fix vertical alignment of "no children" icon

- treemodeladmin/views.py
The TreeModelAdmin index view (TreeIndexView) defines [its own `media` property](https://github.com/cfpb/wagtail-treemodeladmin/blob/a28e28f5c59be7b683673df7402a4f18911fc16a/treemodeladmin/views.py#L148-L152), which pulls in the extra CSS from this package. This is unnecessary, because the base ModelAdmin IndexView from which it inherits already provides a `media` property, which pulls in both extra CSS and JS, if specified by inheriting ModelAdmins.
This functionality exists in all versions of Wagtail supported by this package: [1.13](https://github.com/wagtail/wagtail/blob/v1.13/wagtail/contrib/modeladmin/views.py#L251-L256), [2.5](https://github.com/wagtail/wagtail/blob/v2.5/wagtail/contrib/modeladmin/views.py#L261-L266), and [current …
> Remove unnecessary TreeIndexView media property

- .travis.yml
- README.md
- setup.py
- tox.ini
Remove Python 2.7 and add Python 3.8 to:
* README.rst
* setup.py
* tox.ini
* travis.yml
Add support for Wagtail 2.7 to `tox.ini`, `setup.py`, and `travis.yml`
> Support Wagtail 2.7

- .travis.yml
- CHANGELOG.md
- README.md
- setup.py
- tox.ini
Support production version of Python 3.6 and latest version of Python 3.8
Support production version of Wagtail 1.11 and latest version of Wagtail 2.8
Add Python 3.8 to `travis.yml`
Add Wagtail 2.8 in:
- `README.md`
- `setup.py`
- `tox.ini`
- `README.md`
- `setup.py`
- `tox.ini`
$ tox
```
...
lint: commands succeeded
py36-dj111-wag113: commands succeeded
py36-dj111-wag23: commands succeeded
py36-dj20-wag23: commands succeeded
py36-dj22-wag23: commands succeeded
py36-dj22-wag28: commands succeeded
py38-dj22-wag28: commands succeeded
congratulations :)
```
> Support for testing with Wagtail 2.8 and Python 3.8

- .travis.yml
- CONTRIBUTING.md
- README.md
- pyproject.toml
- setup.py
- tox.ini
- treemodeladmin/__init__.py
- treemodeladmin/apps.py
- treemodeladmin/helpers.py
- treemodeladmin/options.py
- treemodeladmin/templatetags/treemodeladmin_tags.py
- treemodeladmin/tests/settings.py
- treemodeladmin/tests/test_options.py
- treemodeladmin/tests/test_views.py
- treemodeladmin/tests/treemodeladmintest/apps.py
- treemodeladmin/tests/treemodeladmintest/migrations/0001_initial.py
- treemodeladmin/tests/treemodeladmintest/wagtail_hooks.py
- treemodeladmin/tests/urls.py
- treemodeladmin/views.py
Support for Django 2.2 imports
Add black to tox
Support for Wagtail 1.13 in tox and travis
`from __future__ import absolute_import, unicode_literals`
> Remove Wagtail 1.13 support, add Django 2.2 import support, and add Black for autoformatting

- .travis.yml
- README.md
- setup.py
- tox.ini
We should probably only pin Wagtail in this application, and support
the version range for Django that our Wagtail version specifies.
> Remove the Django requirement from this application

- setup.py
- tox.ini
Removed `not_skip` and `recursive` from `tox.ini` to fix
TypeError: __init__() got an unexpected keyword argument 'not_skip'
* recursive
Prior to version 5.0.0, isort wouldn't automatically traverse directories. The --recursive option was necessary to tell it to do so. In 5.0.0 directories are automatically traversed for all Python files, and as such this option is no longer necessary and should simply be removed.
* not_skip
In an earlier version isort had a default skip of __init__.py. To get around that many projects wanted a way to not skip __init__.py or any other files that were automatically skipped in the future by isort. isort no longer has any default skips, so if the value here is __init__.py you can simply remove the setting. …
> Updates to support isort 5.0

- .travis.yml
- README.md
- setup.py
- tox.ini
- treemodeladmin/tests/settings.py
This task is to pin tox environment on Wagtail 2.10 and ensure all tests pass.
There do not appear to be any upgrade considerations that we should be particularly concerned about with 2.10.
- wagtail 2.10 in tox.ini
> Add support for latest Wagtail 2.10 release

- README.md
Replace Travis Badge with the Github Actions Badge
> Replace Travis Badge with Github Actions Badge

- setup.py
- treemodeladmin/tests/settings.py
Change from patch to minor release version as support for Wagtail 2.3 has been dropped.
> Release version 1.3.0 to support Django 3.1

- .github/workflows/test.yml
- README.md
- setup.py
- tox.ini
Hi :wave: 
This PR adds support for the latest Wagtail 2.11 release. 
A new 1.4.0 release of this package should be made to PyPi.
> Support for Wagtail 2.11 release

- .github/workflows/test.yml
- README.md
- setup.py
- tox.ini
- treemodeladmin/templates/treemodeladmin/includes/breadcrumb.html
Wagtail 2.11 is the new LTS release, meaning we can drop support for 2.7. This change also uses Wagtail 2.11's SVG arrow icon in our breadcrumbs in the admin, and versions the next release as 1.5.0.
> Fix breadcrumbs in Wagtail 2.11, drop support for Wagtail < 2.11

- .github/workflows/test.yml
- tox.ini
- treemodeladmin/templatetags/treemodeladmin_tags.py
- treemodeladmin/tests/test_options.py
- treemodeladmin/tests/treemodeladmintest/apps.py
This change updates our tests to run against Python 3.9.
> Update tests to Python 3.9

- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- setup.py
- tox.ini
- treemodeladmin/static/treemodeladmin/css/index.css
- treemodeladmin/tests/settings.py
- treemodeladmin/tests/treemodeladmintest/apps.py
- treemodeladmin/views.py
With [PEP 621 support added to setuptools](https://github.com/pypa/setuptools/pull/2970) last year, and with pip supporting editable installs as of 21.3, we can move to `pyproject.toml` and deprecate `setup.py`. The file remains for legacy pip support.
Because [flake8 does not want to support pyproject.tml yet](https://github.com/PyCQA/flake8/issues/234), unlike all the other tools we use, I’m removing it in favor of [ruff](https://github.com/charliermarsh/ruff).
This change also enables support for Wagtail 3.x by removing the `<3` version pin. This will result in the last release of TreeModelAdmin to support Wagtail < 4.
Wagtail 4.x is not yet supported.
I’ve also brought in some quality-of-life improvements for coverage checking from the Django-Flags tox/GHA setup.
> Support Wagtail 3.x and switch to pyproject.toml

- tox.ini
This commit adds a new `tox -e interactive` that runs a local test server with test data, to make it easier to test this project.
This is a nice feature that [wagtail-localize](https://www.wagtail-localize.org/#how-to-run-tests) has that I've also added to [wagtail-inventory](https://github.com/cfpb/wagtail-inventory#testing).
`tox -e interactive`
This project's README doesn't yet have a section about testing. It would make sense for this to go there.
> Add new interactive tox environment

- .github/workflows/test.yml
- README.md
- pyproject.toml
- tox.ini
- treemodeladmin/templates/treemodeladmin/includes/breadcrumb.html
- treemodeladmin/tests/settings.py
This change adds support for Wagtail 4.2 through 5.1. Wagtail 5.2 changes the breadcrumbs implementation in the admin, and support for it will follow separately.
This drops support for Wagtail 4.1.
> Support Wagtail 4.2 through 5.1

- .github/workflows/test.yml
- README.md
- pyproject.toml
- tox.ini
- treemodeladmin/helpers.py
- treemodeladmin/options.py
- treemodeladmin/templatetags/treemodeladmin_tags.py
- treemodeladmin/tests/settings.py
- treemodeladmin/tests/test_views.py
- treemodeladmin/tests/treemodeladmintest/wagtail_hooks.py
- treemodeladmin/views.py
This updates the package with support for Wagtail 5.2, using the external wagtail-modeladmin rather than the deprecated `wagtail.contrib.modeladmin`.
I've also bumped the top-end Python version to 3.12.
> Support Wagtail 5.2

- .github/workflows/release.yml
- .github/workflows/test.yml
This change updates our PyPI publishing to use API keys by using the official PyPA action and updates the versions of our GitHub Actions used.
This is a first step toward the current PyPI publishing best practices, and our goal for our Python packages should be something like the [PyPA's example GitHub Actions](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/). However, this is a quick and simple update we can make to this and our other packages to ensure we can continue publishing.
> Update PyPI Publishing and GitHub Actions versions

- pyproject.toml
This change removes our upper version pin of Wagtail, enabling (slightly broken) support for Wagtail 6.
With Wagtail 6 there are some additional changes to the breadcrumb and listing templates that we should bring in. The current listing works okay, with the exception of the buttons, but breadcrumbs are entirely broken. The breadcrumbs are a primary means of navigating the model tree, so that'll need to be fixed before this app officially supports Wagtail 6.x.
This change should make this app non-blocking for Wagtail 6.x though.
> Remove upper version pin

- treemodeladmin/templates/treemodeladmin/includes/tree_result_row.html
This fixes the tree navigation icons by using Wagtail's `icon` template tag in place of the `icon` CSS classes.
> Fix navigation icons
